import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.scss";
import { SideBar } from "@/components";
import "../styles/main.scss";

const open_sans = Open_Sans({
  variable: "--open-sans",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Next js project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable}`}>
        <SideBar />
        {children}
      </body>
    </html>
  );
}
